trigger:
  branches:
    include:
      - main
  paths:
    include:
      - sbg-tools-cloudforge-deployment/cloudformation-deployer/*

parameters:
- name: IMAGE_TAG
  displayName: 'Docker Image Tag e.g: PROD-1.0.0'
  type: string

variables:
- name: AWS_ACCOUNT_ID
  value: '573185292006'
- name: AWS_REGION
  value: 'af-south-1'
- name: ECR_REPOSITORY
  value: 'cloudforge/cloudforge'
- name: IMAGE_TAG
  value: ${{ parameters.IMAGE_TAG }}

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build and Push to ECR'
  jobs:
  - job: BuildPush
    displayName: 'Build Docker Image and Push to ECR'
    steps:
    - task: AWSShellScript@1
      displayName: 'Configure AWS CLI and ECR Login'
      inputs:
        awsCredentials: 'azure_aws_connection_tools'
        regionName: '$(AWS_REGION)'
        scriptType: 'inline'
        inlineScript: |
          # Get ECR login token
          aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
          
          # Create ECR repository if it doesn't exist
          aws ecr describe-repositories --repository-names $(ECR_REPOSITORY) --region $(AWS_REGION) || \
          aws ecr create-repository --repository-name $(ECR_REPOSITORY) --region $(AWS_REGION)

    - task: checkmarx.checkmarx-ast-azure-plugin.cx-scan-task.Checkmarx AST@3
      displayName: 'Checkmarx AST'
      inputs:
        CheckmarxService: 'Checkmarx One - SBG DevOps'
        tenantName: Standardbank
        
    - script: |
        docker buildx create --use --name multiarch
        docker buildx inspect --bootstrap
      displayName: 'Setup Docker Buildx'

    - script: |
        docker buildx build --platform linux/amd64,linux/arm64 -f $(Build.SourcesDirectory)/cloudformation-deployer/Dockerfile -t $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(IMAGE_TAG) --push $(Build.SourcesDirectory)/cloudformation-deployer
      displayName: 'Build and Push Multi-Platform Docker Image'
        
    - script: |
        echo "Multi-platform image pushed successfully:"
        echo "$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(ECR_REPOSITORY):$(IMAGE_TAG)"
      displayName: 'Output Image URI'